import { Spread } from './types';

export const SPREADS: Spread[] = [
  {
    id: 0,
    name: "Le Mat",
    title: "0. Le Mat",
    purpose: "Pour dépasser tout ce qui nous retient d'avancer.",
    cardPositions: [
      { number: 1, meaning: "Ce que représente le grand saut pour moi" },
      { number: 2, meaning: "Ce que m'apporte mon expérience" },
      { number: 3, meaning: "Ce qui me retient d'y aller" },
      { number: 4, meaning: "Ce à quoi je dois faire attention" },
      { number: 5, meaning: "Ce que je tirerai du grand saut" },
    ],
    description: "Le Mat part à l'aventure : il se jette à l'eau avec confiance, il se lance sans réfléchir aux conséquences. Peut-être est-il fou, mais au moins il y va !",
  },
  {
    id: 1,
    name: "Le Bateleur",
    title: "I. Le Bateleur",
    purpose: "Pour définir son désir et s'amener à le réaliser.",
    cardPositions: [
      { number: 1, meaning: "Mon désir (aspect 1)" },
      { number: 2, meaning: "Mon désir (aspect 2)" },
      { number: 3, meaning: "Mon désir (aspect 3)" },
      { number: 4, meaning: "Moyen concret (aspect 1)" },
      { number: 5, meaning: "Moyen concret (aspect 2)" },
      { number: 6, meaning: "Moyen concret (aspect 3)" },
      { number: 7, meaning: "Ce que cela m'amènera (aspect 1)" },
      { number: 8, meaning: "Ce que cela m'amènera (aspect 2)" },
      { number: 9, meaning: "Ce que cela m'amènera (aspect 3)" },
    ],
    description: "Le Bateleur a les éléments à sa disposition, sait ce qu'il veut, et le communique dans le matériel : c'est celui qui agit.",
  },
  {
    id: 2,
    name: "La Papesse",
    title: "II. La Papesse",
    purpose: "Pour interroger les raisons cachées d'une situation.",
    cardPositions: [
      { number: 1, meaning: "La vérité de cette situation" },
      { number: 2, meaning: "Comment cela m'affecte" },
      { number: 3, meaning: "Pourquoi je ne l'ai pas vu plus tôt" },
      { number: 4, meaning: "Ce que cette connaissance m'apporte" },
    ],
    description: "La Papesse est assise, silencieuse, devant un voile qui cache des mystères. S'il y a un voile, c'est que quelque chose est caché... l'évidence est trompeuse.",
  },
  {
    id: 3,
    name: "L'Impératrice",
    title: "III. L'Impératrice",
    purpose: "Pour débloquer sa créativité et préciser ce que l'on a à apporter au monde.",
    cardPositions: [
      { number: 1, meaning: "Ce que j'ai en moi" },
      { number: 2, meaning: "Ce qui me féconde" },
      { number: 3, meaning: "Ce que je donne" },
    ],
    description: "Cet arcane représente le Féminin en majesté : la puissance de génération, la fertilité, tout ce qui représente le fait de créer quelque chose à partir de soi.",
  },
  {
    id: 4,
    name: "L'Empereur",
    title: "IV. L'Empereur",
    purpose: "Pour mettre les choses au clair une fois pour toutes.",
    cardPositions: [
      { number: 1, meaning: "Ce que je veux obtenir" },
      { number: 2, meaning: "La situation réelle" },
      { number: 3, meaning: "La règle à suivre" },
      { number: 4, meaning: "Ce qui va se passer" },
    ],
    description: "Cet arcane représente le Masculin en majesté : l'autorité, la règle, la structure, le cadre, la Loi, toutes ces choses qui sont comme ça et pas autrement.",
  },
  {
    id: 5,
    name: "Le Pape",
    title: "V. Le Pape",
    purpose: "Pour savoir comment se placer par rapport à une situation critique.",
    cardPositions: [
      { number: 1, meaning: "Leçon que je peux donner" },
      { number: 2, meaning: "Leçon qu'on doit me donner" },
      { number: 3, meaning: "Raison de la situation" },
      { number: 4, meaning: "Sens supérieur de tout cela" },
      { number: 5, meaning: "Enseignement à retenir" },
    ],
    description: "Imposant mais bienveillant, le Pape enseigne. Il apprend à écouter et fait découvrir ce qu'il y a au-delà du monde matériel : le sacré.",
  },
  {
    id: 6,
    name: "L'Amoureux",
    title: "VI. L'Amoureux",
    purpose: "En cas d'hésitation entre deux choix, deux projets, deux possibilités.",
    cardPositions: [
      { number: 1, meaning: "Mon besoin dans cette situation" },
      { number: 2, meaning: "Mon désir ou ma direction" },
      { number: 3, meaning: "Choix 1" },
      { number: 4, meaning: "Ce que le choix 1 donne" },
      { number: 5, meaning: "Choix 2" },
      { number: 6, meaning: "Ce que le choix 2 donne" },
    ],
    description: "L'Amoureux n'a pas plus de raison d'aller d'un côté que de l'autre ; c'est bien que la raison ne suffit pas ! La sensibilité a le dernier mot pour les choix qui comptent.",
  },
  {
    id: 7,
    name: "Le Chariot",
    title: "VII. Le Chariot",
    purpose: "Pour savoir à quoi s'attendre ou garder le cap quand on s'est lancé un défi ambitieux.",
    cardPositions: [
      { number: 1, meaning: "Ce que ce projet m'apporte / Objectif" },
      { number: 2, meaning: "Obstacle 1" },
      { number: 3, meaning: "Force 1 (pour surmonter)" },
      { number: 4, meaning: "Obstacle 2" },
      { number: 5, meaning: "Force 2 (pour surmonter)" },
    ],
    description: "Il suffit d'avoir pris une décision pour s'en rendre compte : nous ne nous entendons pas avec nous-mêmes. Des passions contradictoires nous tiraillent. Peu importe : le cap est bon !",
  },
  {
    id: 8,
    name: "La Force",
    title: "VIII. La Force",
    purpose: "Pour se réaligner avec ses instincts ou laisser s'exprimer sa passion.",
    cardPositions: [
      { number: 1, meaning: "Ce que je crains, ou Mon blocage" },
      { number: 2, meaning: "Ma force fondamentale" },
      { number: 3, meaning: "Mon désir, ou comment les réconcilier" },
    ],
    description: "Cette passion qui gronde en nous et nous effraie, il vaut mieux entendre son message que tenter de l'étouffer.",
  },
  {
    id: 9,
    name: "L'Hermite",
    title: "IX. L'Ermite",
    purpose: "Pour se poser en guide équilibré.",
    cardPositions: [
      { number: 1, meaning: "Ce que j'ai de particulier" },
      { number: 2, meaning: "Ce sur quoi je peux m'appuyer" },
      { number: 3, meaning: "Ce que j'apprends sur mon chemin" },
      { number: 4, meaning: "Comment je peux aider les autres" },
    ],
    description: "Sur son chemin, l'Hermite est seul ; cela ne l'empêche pas d'élever sa lanterne, pour que sa lumière vacillante, au loin, informe les autres qu'il y a bien un chemin.",
  },
  {
    id: 10,
    name: "La Roue de Fortune",
    title: "X. La Roue de Fortune",
    purpose: "Pour reconnaître et éviter les obstacles qui s'annoncent.",
    cardPositions: [
      { number: 1, meaning: "Ce dont je dois tenir compte" },
      { number: 2, meaning: "Ce qui peut m'attirer des ennuis" },
      { number: 3, meaning: "Ce qui améliorera ma situation" },
      { number: 4, meaning: "Ce dont je ne dois pas dévier" },
    ],
    description: "Les circonstances nous emportent, parfois vers le haut, et parfois vers le bas ; celui qui ne veut pas en être victime doit utiliser son épée de jugement pour trancher.",
  },
  {
    id: 11,
    name: "La Justice",
    title: "XI. La Justice",
    purpose: "Pour rectifier le tir dans les situations d'incertitude morale.",
    cardPositions: [
      { number: 1, meaning: "Ce qui me définit" },
      { number: 2, meaning: "La mauvaise action" },
      { number: 3, meaning: "Ses conséquences" },
      { number: 4, meaning: "La bonne action" },
      { number: 5, meaning: "La leçon que je retiens" },
      { number: 6, meaning: "Sur quoi m'appuyer pour agir concrètement" },
    ],
    description: "La Justice du Tarot n'a pas les yeux bandés ; elle nous regarde en face, d'un oeil qui sonde l'âme. Face à un tel regard, on ne peut que se demander : ai-je été fidèle à moi-même ?",
  },
  {
    id: 12,
    name: "Le Pendu",
    title: "XII. Le Pendu",
    purpose: "Pour tirer le meilleur d'une situation bloquée.",
    cardPositions: [
      { number: 1, meaning: "Ce que je ne peux plus faire" },
      { number: 2, meaning: "Ce que je dois sacrifier" },
      { number: 3, meaning: "Ce à quoi cela m'oblige à me confronter" },
      { number: 4, meaning: "Leçon et but que j'obtiens" },
    ],
    description: "Tête en bas, le Pendu a tout perdu : sa place, ses biens... Ne reste plus que l'essentiel : lui-même.",
  },
  {
    id: 13,
    name: "La Mort",
    title: "XIII. La Mort",
    purpose: "Pour encourager le changement et faciliter le passage d'une étape à une autre.",
    cardPositions: [
      { number: 1, meaning: "Ce dont j'avais besoin avant" },
      { number: 2, meaning: "Là où j'en suis maintenant" },
      { number: 3, meaning: "Ce vers quoi je me dirige" },
      { number: 4, meaning: "Ce qui me bloque aujourd'hui" },
      { number: 5, meaning: "Comment faciliter la transition" },
    ],
    description: "Cet étrange squelette agriculteur n'a qu'un travail à faire : débarrasser de l'obsolète pour faire place au nouveau.",
  },
  {
    id: 14,
    name: "Tempérance",
    title: "XIV. Tempérance",
    purpose: "Pour réconcilier deux objectifs qui s'excluent en apparence.",
    cardPositions: [
      { number: 1, meaning: "Objectif 1" },
      { number: 2, meaning: "Objectif 2" },
      { number: 3, meaning: "Le lien que je n'avais pas vu" },
      { number: 4, meaning: "Ce dont j'ai besoin, matériellement" },
      { number: 5, meaning: "Ce dont j'ai besoin, spirituellement" },
      { number: 6, meaning: "Le conseil" },
    ],
    description: "Deux coupes bien différentes et un jet sous pression : Tempérance est l'ange qui relie deux mondes différents, deux choses contradictoires au prix d'un effort constant.",
  },
  {
    id: 15,
    name: "Le Diable",
    title: "XV. Le Diable",
    purpose: "Pour se libérer d'une situation où l'on se sent coincé.",
    cardPositions: [
      { number: 1, meaning: "Ce à quoi je suis lié" },
      { number: 2, meaning: "Le bénéfice secondaire (ce que j'en tire)" },
      { number: 3, meaning: "La réalité des choses" },
      { number: 4, meaning: "Ce que j'ai en mains pour en sortir" },
      { number: 5, meaning: "Comment l'appliquer" },
    ],
    description: "Deux petits diablotins sont enchaînés au pied d'un monstre. À y regarder de plus près, leurs chaînes ne sont pas si serrées que cela...",
  },
  {
    id: 16,
    name: "La Maison-Dieu",
    title: "XVI. La Maison-Dieu",
    purpose: "Pour mieux appréhender un changement imprévu et en tirer profit.",
    cardPositions: [
      { number: 1, meaning: "Ce dont j'étais certain" },
      { number: 2, meaning: "La situation réelle" },
      { number: 3, meaning: "Facteur du changement" },
      { number: 4, meaning: "Ce dont je dois me débarrasser (aspect 1)" },
      { number: 5, meaning: "Ce dont je dois me débarrasser (aspect 2)" },
      { number: 6, meaning: "Ce dont je dois me débarrasser (aspect 3)" },
      { number: 7, meaning: "Ce que je peux conserver (aspect 1)" },
      { number: 8, meaning: "Ce que je peux conserver (aspect 2)" },
      { number: 9, meaning: "Ce que je peux conserver (aspect 3)" },
    ],
    description: "La Maison-Dieu est une construction qui vole en éclats lorsqu'un événement extérieur vient la remettre en cause : visiblement, ça n'était pas comme on pensait.",
  },
  {
    id: 17,
    name: "L'Etoile",
    title: "XVII. L'Etoile",
    purpose: "Pour définir votre idéal et savoir l'exprimer sur tous les plans.",
    cardPositions: [
      { number: 1, meaning: "Mon désir essentiel" },
      { number: 2, meaning: "Comment je m'exprime dans cette voie" },
      { number: 3, meaning: "Ce que j'ai à donner (domaine matériel)" },
      { number: 4, meaning: "Ce que j'ai à donner (domaine spirituel)" },
    ],
    description: "Notre place n'est pas de l'ordre de la construction : elle est, tout simplement. La femme de l'Etoile sait qu'elle est parfaitement à sa place.",
  },
  {
    id: 18,
    name: "La Lune",
    title: "XVIII. La Lune",
    purpose: "Pour porter la lumière sur notre part d'ombre.",
    cardPositions: [
      { number: 1, meaning: "Les espoirs et les craintes (ou : Mon idéal)" },
      { number: 2, meaning: "Ce que je préfèrerais ne pas savoir" },
      { number: 3, meaning: "L'esprit domestiqué" },
      { number: 4, meaning: "L'instinct sauvage" },
    ],
    description: "Mettons au jour ces parts refoulées de notre inconscient : le chien domestiqué, le loup sauvage, et la primitive écrevisse, qui marche à reculons dans la fange.",
  },
  {
    id: 19,
    name: "Le Soleil",
    title: "XIX. Le Soleil",
    purpose: "Pour retrouver la bonne humeur et rayonner.",
    cardPositions: [
      { number: 1, meaning: "Ce qu'il y a de plus aimable en moi" },
      { number: 2, meaning: "Ce que j'ai réussi à comprendre" },
      { number: 3, meaning: "Ce que j'apporte de mieux au monde" },
      { number: 4, meaning: "Ce que j'apporte de mieux aux autres" },
      { number: 5, meaning: "Ma plus grande force" },
      { number: 6, meaning: "Ma plus belle force" },
      { number: 7, meaning: "Ma force communicative" },
    ],
    description: "L'être réconcilié avec lui-même rayonne : sa joie et sa chaleur sont communicatives.",
  },
  {
    id: 20,
    name: "Le Jugement",
    title: "XX. Le Jugement",
    purpose: "Pour trouver sa vocation et/ou l'âme soeur...",
    cardPositions: [
      { number: 1, meaning: "Mon idéal" },
      { number: 2, meaning: "Comment se manifeste l'appel" },
      { number: 3, meaning: "Ce que répondre m'apportera" },
      { number: 4, meaning: "Moyens d'y répondre au mieux" },
      { number: 5, meaning: "Ce que je laisse derrière moi" },
    ],
    description: "L'ange reconnaît les Justes, et les Justes l'accueillent : un appel auquel on ne se soustrait pas, sous le signe de la reconnaissance mutuelle.",
  },
  {
    id: 21,
    name: "Le Monde",
    title: "XXI. Le Monde",
    purpose: "Pour faire le bilan et reprendre confiance.",
    cardPositions: [
      { number: 1, meaning: "Ce que je suis et que j'apporte au monde" },
      { number: 2, meaning: "Ce qui me protège" },
      { number: 3, meaning: "Ce qui me soutient" },
      { number: 4, meaning: "Ma force passionnelle" },
      { number: 5, meaning: "Ma force émotionnelle" },
      { number: 6, meaning: "Ma force intellectuelle" },
      { number: 7, meaning: "Ma force matérielle" },
    ],
    description: "L'éveillé est Dieu est le Monde : l'accomplissement parfait de celui qui fait partie du Tout.",
  },
];
